name: CI for React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test App
        run: npm run test
